In [6]:
import numpy as np

In [7]:
np_array = np.array()

TypeError: array() missing required argument 'object' (pos 0)

In [8]:
np_array = np.array(object=None)

In [9]:
np_array

array(None, dtype=object)

In [10]:
print(type(np_array))

<class 'numpy.ndarray'>


In [11]:
print(len(np_array))

TypeError: len() of unsized object

In [12]:
np_array = np.array([])

In [13]:
np_array

array([], dtype=float64)

In [16]:
len(np_array)

0

In [17]:
type(np_array)

numpy.ndarray

In [ ]:
# creating 1-D array

In [21]:
some_list = [1,2,3,4,5]
some_list

[1, 2, 3, 4, 5]

In [23]:
array = np.array(object=some_list)

In [24]:
print(type(array))
len(array)

<class 'numpy.ndarray'>


5

In [25]:
array.dtype

dtype('int64')

In [26]:
np_array = np.array(['apple','orange','banana','watermelon','jackfruit'])

In [30]:
type(np_array)


numpy.ndarray

In [31]:
np_array.dtype

dtype('<U10')

In [33]:
np_array = np.array([1,2,3],dtype='float')
np_array

array([1., 2., 3.])

In [35]:
np_array = np.array([-1, 5.5, 2, 3.5])
np_array

array([-1. ,  5.5,  2. ,  3.5])

Note that the integers have been conveted to floats.Arrys cannot be of composite data types.

In [36]:
np_array = np.array(['apple',2,'banana',4.5])
np_array

array(['apple', '2', 'banana', '4.5'], dtype='<U32')

Example 3  ::
Creating arrays from tuples

In [37]:
some_tuple = (-5,1,-4,7,2)
print(some_tuple, type(some_tuple))


(-5, 1, -4, 7, 2) <class 'tuple'>


In [40]:
np_array = np.array(some_tuple)
print(np_array,type(np_array))

[-5  1 -4  7  2] <class 'numpy.ndarray'>


EXample 4 :: Creating arrays frpm lists of different data structures


In [41]:
mixed_list = [[1,2,3],'New York',5.6, -10, 'John']
mixed_list

[[1, 2, 3], 'New York', 5.6, -10, 'John']

In [43]:
mixed_list[0]


[1, 2, 3]

In [44]:
mixed_list[3]

-10

In [45]:
np_array = np.array(object=mixed_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [47]:
np_array = np.array(object=mixed_list, dtype='object')
print(np_array, type(np_array))

[list([1, 2, 3]) 'New York' 5.6 -10 'John'] <class 'numpy.ndarray'>
